inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 4.0
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/*_schema.rb"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "storage/**/*"
    - "tmp/**/*"

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
