FROM ruby:4.0-slim

RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev curl git nodejs npm postgresql-client && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /rails

RUN gem install bundler

EXPOSE 3000 5173

CMD ["bin/dev"]