FROM ruby:4.0.6-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      chromium \
      chromium-driver \
      curl \
      git \
      libpq-dev \
      libsqlite3-dev \
      libvips \
      libyaml-dev \
      nodejs \
      npm \
      pkg-config \
      postgresql-client \
      sqlite3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /rails

ENV BUNDLE_PATH="/usr/local/bundle" \
    CHROME_BIN="/usr/bin/chromium" \
    RAILS_ENV="development"

RUN gem install bundler -v 4.0.16

EXPOSE 3000 3036

CMD ["bin/dev"]
